name: Daily Build
on:
  schedule:
    - cron: '0 6 * * * '
jobs:
  build:
    env:
      LIFX_TOKEN: ${{ secrets.LIFX_TOKEN }}
      LIFX_BULB_ID: ${{ secrets.LIFX_BULB_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Deps
        run: yarn
      - name: Cache .cache
        id: cache-cache
        uses: actions/cache@v1
        with:
          path: .cache
          key: ${{ runner.os }}-lannonbr-com-gatsby-cache-${{ hashFiles('.cache/**') }}
      - name: Cache gatsby public folder
        id: cache-public
        uses: actions/cache@v1
        with:
          path: public
          key: ${{ runner.os }}-lannonbr-com-gatsby-public-${{ hashFiles('public/**') }}
      - name: Build Site
        run: yarn build
      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify-cli deploy --dir=public --prod
      - name: Trigger light to go green on success
        if: success()
        uses: lannonbr/lifx-trigger-action@1.0.0
        with:
          color: green
      - name: Trigger light to go red on failure
        if: failure()
        uses: lannonbr/lifx-trigger-action@1.0.0
        with:
          color: red
