name: Build on push
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  toast-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14.16.x'
      - name: Install Deps
        run: yarn install
      - name: Build Site
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          HONEYCOMB_WRITE_KEY: ${{ secrets.HONEYCOMB_WRITE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn build
      - name: Upload public dir as artifact
        uses: actions/upload-artifact@v2
        with:
          name: public-dir
          path: public/
  gen-og-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build files
        run: |
          cd .github/actions/gen-og-images-action
          yarn
          yarn build
          node index.js
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: og-images
          path: .github/actions/gen-og-images-action/dist/posts/
  push-css-stats:
    runs-on: ubuntu-latest
    needs: [toast-build]
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CSS_STATS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CSS_STATS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: get public dir
        uses: actions/download-artifact@v2
        with:
          name: public-dir
          path: public
      - uses: lannonbr/save-css-stats-action@v1
        with:
          filepath: public/style.css
          dynamo-table-name: lannonbr.com-css-stats
  deploy-build:
    runs-on: ubuntu-latest
    needs: [gen-og-images, toast-build]
    env:
      LIFX_TOKEN: ${{ secrets.LIFX_TOKEN }}
      LIFX_BULB_ID: ${{ secrets.LIFX_BULB_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: get public dir
        uses: actions/download-artifact@v2
        with:
          name: public-dir
          path: public
      - name: get og-images dir
        uses: actions/download-artifact@v2
        with:
          name: og-images
          path: public/og-images/blog/
      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          wget https://github.com/lannonbr/netlify_deploy/releases/download/pre-release-86d0ca03f920ab445a3daf4c52fd39ef02a12922/netlify-deploy-linux-86d0ca03f920ab445a3daf4c52fd39ef02a12922.tar.gz
          tar -xvf netlify-deploy-linux-86d0ca03f920ab445a3daf4c52fd39ef02a12922.tar.gz

          ./release/netlify_deploy --path public --prod
      - name: Trigger light to go green on success
        if: success()
        uses: lannonbr/lifx-trigger-action@1.0.0
        with:
          color: green
      - name: Trigger light to go red on failure
        if: failure()
        uses: lannonbr/lifx-trigger-action@1.0.0
        with:
          color: red
