name: Build on push
on: push
jobs:
  build:
    env:
      LIFX_TOKEN: ${{ secrets.LIFX_TOKEN }}
      LIFX_BULB_ID: ${{ secrets.LIFX_BULB_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn
          yarn build
          npx netlify-cli deploy --dir=public --prod
      - name: Trigger light to go green on success
        if: success()
        uses: ./.github/actions/lifx-trigger-action
        with:
          color: green
      - name: Trigger light to go red on failure
        if: failure()
        uses: ./.github/actions/lifx-trigger-action
        with:
          color: red
